djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkkdjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkkdjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkkasdasdadasdasd
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkks
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
sssssssskljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkkdjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkkdjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk

sssonst uname = 'zhangs'
sssonst age =18
ssskkkkkkkkkkkkkkk            
ssskkkkkksssssssssskkk            
ssskkhellsssssssssskkk            
ssskkkkkksssssssssskkk            
sssjkjskdssssssssssdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
sssello;123;12;123s
sssjkjskdjalksjdkajsldkasdjlajsdkljaksasdas123jdlkajskldjalksjdajskkjdjklajsdklajsdkkl;123;
sssjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
sssjkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk




ishjdahsjkdhjsakhdjkahsdhajkshdjhasjdaksdhkahsdjkhajksdhjashdkaskhdkahskdhasdhkashdk

defineAsyncComponentd

const abc = 123
a
d

asd
a
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalkssssjdajskkjdjklajsdklajsdkkdzzzzzz
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjd ajsldkasdjlajsdkljaksjdlkajskldjjalsdasdksjdajskkjdjklajsdklajsdkkd
djkjskdjalkssjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkksiasdadasdasd
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
kajsldkas






k
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjdkajsldkasdjlajsdklja1sjdlkajskldjalksjdajskkjdjklajsdklajsdkk
djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk

sudongyu aa = 1nihao
sudongyu abc = 2

  djkjskdjalksjdkajsldkasdjlajsdkljaksjdlkajskldjalksjdajskkjdjklajsdklajsdkk;l;l;l;l;l;lsssssssssssssssss
sudongyu hellosss
  123 b = 123 123123123123
}
const a = helloWorldnihao
123 
123
123
 <di123</di>
`123123`

this is a juzi.
this is a juzi!
this is 1a2 sudongyuujuzi?;;
this is 1a2 juzi?;;
this is 1a2 juzi?;;
function 11(_name, ae){
  return _name + age
}
entire
iconst a = 'hello world';
const a = 'hello worldi';
const uname = 'nihao'
